In [1]:
import pandas as pd

In [4]:
base = pd.read_csv('/content/drive/MyDrive/00. Trabalho/RD202410.csv',
                   sep=';',
                   low_memory=False)

In [11]:
pd.options.display.max_info_columns = 113
base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1188544 entries, 0 to 1188543
Data columns (total 113 columns):
 #    Column      Dtype
---   ------      -----
 0    UF_ZI       int64
 1    ANO_CMPT    int64
 2    MES_CMPT    int64
 3    ESPEC       int64
 4    CGC_HOSP    float64
 5    N_AIH       int64
 6    IDENT       int64
 7    CEP         int64
 8    MUNIC_RES   int64
 9    NASC        int64
 10   SEXO        int64
 11   UTI_MES_IN  int64
 12   UTI_MES_AN  int64
 13   UTI_MES_AL  int64
 14   UTI_MES_TO  int64
 15   MARCA_UTI   int64
 16   UTI_INT_IN  int64
 17   UTI_INT_AN  int64
 18   UTI_INT_AL  int64
 19   UTI_INT_TO  int64
 20   DIAR_ACOM   int64
 21   QT_DIARIAS  int64
 22   PROC_SOLIC  int64
 23   PROC_REA    int64
 24   VAL_SH      float64
 25   VAL_SP      float64
 26   VAL_SADT    float64
 27   VAL_RN      float64
 28   VAL_ACOMP   float64
 29   VAL_ORTP    float64
 30   VAL_SANGUE  float64
 31   VAL_SADTSR  float64
 32   VAL_TRANSP  float64
 33   VAL_OBSANG  float64
 34   VAL_PED1AC  float64
 35   VAL_TOT     float64
 36   VAL_UTI     float64
 37   US_TOT      float64
 38   DT_INTER    int64
 39   DT_SAIDA    int64
 40   DIAG_PRINC  object
 41   DIAG_SECUN  int64
 42   COBRANCA    int64
 43   NATUREZA    int64
 44   NAT_JUR     int64
 45   GESTAO      int64
 46   RUBRICA     int64
 47   IND_VDRL    int64
 48   MUNIC_MOV   int64
 49   COD_IDADE   int64
 50   IDADE       int64
 51   DIAS_PERM   int64
 52   MORTE       int64
 53   NACIONAL    int64
 54   NUM_PROC    float64
 55   CAR_INT     int64
 56   TOT_PT_SP   int64
 57   CPF_AUT     float64
 58   HOMONIMO    int64
 59   NUM_FILHOS  int64
 60   INSTRU      int64
 61   CID_NOTIF   object
 62   CONTRACEP1  int64
 63   CONTRACEP2  int64
 64   GESTRISCO   int64
 65   INSC_PN     int64
 66   SEQ_AIH5    int64
 67   CBOR        int64
 68   CNAER       int64
 69   VINCPREV    int64
 70   GESTOR_COD  int64
 71   GESTOR_TP   int64
 72   GESTOR_CPF  int64
 73   GESTOR_DT   float64
 74   CNES        int64
 75   CNPJ_MANT   float64
 76   INFEHOSP    float64
 77   CID_ASSO    int64
 78   CID_MORTE   int64
 79   COMPLEX     int64
 80   FINANC      int64
 81   FAEC_TP     float64
 82   REGCT       int64
 83   RACA_COR    int64
 84   ETNIA       object
 85   SEQUENCIA   int64
 86   REMESSA     object
 87   AUD_JUST    object
 88   SIS_JUST    object
 89   VAL_SH_FED  float64
 90   VAL_SP_FED  float64
 91   VAL_SH_GES  float64
 92   VAL_SP_GES  float64
 93   VAL_UCI     float64
 94   MARCA_UCI   int64
 95   DIAGSEC1    object
 96   DIAGSEC2    object
 97   DIAGSEC3    object
 98   DIAGSEC4    object
 99   DIAGSEC5    object
 100  DIAGSEC6    object
 101  DIAGSEC7    object
 102  DIAGSEC8    object
 103  DIAGSEC9    object
 104  TPDISEC1    int64
 105  TPDISEC2    int64
 106  TPDISEC3    int64
 107  TPDISEC4    int64
 108  TPDISEC5    int64
 109  TPDISEC6    int64
 110  TPDISEC7    int64
 111  TPDISEC8    int64
 112  TPDISEC9    int64
dtypes: float64(26), int64(72), object(15)
memory usage: 1.0+ GB

In [16]:
pd.set_option('display.float_format', '{:.2f}'.format)
base.describe()

,UF_ZI,ANO_CMPT,MES_CMPT,ESPEC,CGC_HOSP,N_AIH,IDENT,CEP,MUNIC_RES,NASC,SEXO,UTI_MES_IN,UTI_MES_AN,UTI_MES_AL,UTI_MES_TO,MARCA_UTI,UTI_INT_IN,UTI_INT_AN,UTI_INT_AL,UTI_INT_TO,DIAR_ACOM,QT_DIARIAS,PROC_SOLIC,PROC_REA,VAL_SH,VAL_SP,VAL_SADT,VAL_RN,VAL_ACOMP,VAL_ORTP,VAL_SANGUE,VAL_SADTSR,VAL_TRANSP,VAL_OBSANG,VAL_PED1AC,VAL_TOT,VAL_UTI,US_TOT,DT_INTER,DT_SAIDA,DIAG_SECUN,COBRANCA,NATUREZA,NAT_JUR,GESTAO,RUBRICA,IND_VDRL,MUNIC_MOV,COD_IDADE,IDADE,DIAS_PERM,MORTE,NACIONAL,NUM_PROC,CAR_INT,TOT_PT_SP,CPF_AUT,HOMONIMO,NUM_FILHOS,INSTRU,CONTRACEP1,CONTRACEP2,GESTRISCO,INSC_PN,SEQ_AIH5,CBOR,CNAER,VINCPREV,GESTOR_COD,GESTOR_TP,GESTOR_CPF,GESTOR_DT,CNES,CNPJ_MANT,INFEHOSP,CID_ASSO,CID_MORTE,COMPLEX,FINANC,FAEC_TP,REGCT,RACA_COR,SEQUENCIA,VAL_SH_FED,VAL_SP_FED,VAL_SH_GES,VAL_SP_GES,VAL_UCI,MARCA_UCI,TPDISEC1,TPDISEC2,TPDISEC3,TPDISEC4,TPDISEC5,TPDISEC6,TPDISEC7,TPDISEC8,TPDISEC9
count,1188544.00,1188544.00,1188544.00,1188544.00,905139.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,0.00,1188544.00,1188544.00,0.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,0.00,1188544.00,604135.00,0.00,1188544.00,1188544.00,1188544.00,1188544.00,88964.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00,1188544.00
mean,328597.60,2024.00,10.00,2.90,35302591849635.61,3300202669779.52,1.04,50895820.61,329140.47,19804695.33,2.13,0.00,0.00,0.00,0.61,6.90,0.00,0.00,0.00,0.05,2.18,4.46,352840843.41,353534921.54,1304.98,331.76,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1751.84,407.38,289.56,20240723.33,20240961.93,0.00,20.72,0.00,2312.60,1.44,0.00,0.07,329273.50,3.92,43.46,4.95,0.04,10.19,NaN,1.73,0.00,NaN,0.00,0.06,0.07,0.22,0.14,1.00,2732649153.30,0.00,37.12,0.10,0.00,1.29,0.19,6181801951.79,NaN,2773054.15,26963730753982.56,NaN,0.00,0.00,2.09,5.85,40074.06,1581.99,2.25,14368.60,72.99,40.51,0.92,0.67,10.20,0.01,0.30,0.04,0.02,0.01,0.00,0.00,0.00,0.00,0.00
std,93380.61,0.00,0.00,5.09,27963191287067.95,933918772035.83,0.38,28150968.41,93548.82,246193.33,0.99,0.00,0.00,0.00,3.06,21.91,0.00,0.00,0.00,0.91,4.45,6.46,54088664.13,54241858.23,3368.65,939.98,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,4324.67,2064.69,714.82,5274.40,87.00,0.00,16.01,0.00,1332.97,0.50,0.00,0.26,93494.67,0.36,24.29,7.32,0.20,4.50,NaN,0.54,0.00,NaN,0.05,0.44,0.44,1.36,1.14,0.06,35911471573.10,0.09,3676.51,8.90,0.03,8.51,0.39,17785698278.03,NaN,1905490.22,23821747961063.36,NaN,0.00,0.00,0.29,0.53,16.10,2955.51,1.50,22099.30,608.07,514.85,29.24,24.99,172.62,0.10,0.60,0.21,0.14,0.09,0.06,0.04,0.03,0.02,0.01
min,110000.00,2024.00,10.00,1.00,618000151.00,1123101331210.00,1.00,1001000.00,110001.00,18941118.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,201010038.00,201010038.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,20080101.00,20240501.00,0.00,11.00,0.00,1015.00,1.00,0.00,0.00,110001.00,2.00,0.00,0.00,0.00,10.00,NaN,1.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,35.00,6874000156.00,NaN,0.00,0.00,2.00,4.00,40024.00,0.00,1.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,261160.00,2024.00,10.00,1.00,10848190000155.00,2624500476719.75,1.00,26383330.00,261540.00,19600801.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,303100044.00,303100044.00,268.60,55.96,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,363.90,0.00,60.14,20240913.00,20240920.00,0.00,12.00,0.00,1031.00,1.00,0.00,0.00,261390.00,4.00,25.00,1.00,0.00,10.00,NaN,1.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,2084473.00,7731102000126.00,NaN,0.00,0.00,2.00,6.00,40080.00,0.00,1.00,542.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
50%,330390.00,2024.00,10.00,2.00,27080605002300.00,3324108384504.00,1.00,55020100.00,330452.00,19810411.00,3.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,2.00,310010039.00,310010039.00,471.75,136.44,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,674.11,0.00,111.42,20241002.00,20241007.00,0.00,12.00,0.00,1244.00,1.00,0.00,0.00,330455.00,4.00,43.00,2.00,0.00,10.00,NaN,2.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,2399644.00,18431312001359.00,NaN,0.00,0.00,2.00,6.00,40080.00,0.00,3.00,4790.50,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
75%,410000.00,2024.00,10.00,3.00,53221255001970.00,4124101545830.75,1.00,74957090.00,410460.00,19990906.00,3.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2.00,5.00,408050683.00,408060360.00,907.44,285.31,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1275.94,0.00,210.89,20241014.00,20241018.00,0.00,22.00,0.00,3999.00,2.00,0.00,0.00,410420.00,4.00,64.00,6.00,0.00,10.00,NaN,2.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,2753278.00,46374500000194.00,NaN,0.00,0.00,2.00,6.00,40080.00,0.00,3.00,19213.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
max,530000.00,2024.00,10.00,87.00,98714876000102.00,9924300004564.00,5.00,99990000.00,530010.00,20241031.00,3.00,0.00,0.00,0.00,226.00,99.00,0.00,0.00,0.00,92.00,282.00,308.00,506020134.00,506020134.00,188418.75,56564.49,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,188487.47,149100.00,31154.95,20241031.00,20241031.00,0.00,67.00,0.00,3999.00,2.00,0.00,1.00,530010.00,5.00,99.00,343.00,1.00,349.00,NaN,6.00,0.00,NaN,2.00,85.00,4.00,13.00,13.00,1.00,999999999999.00,64.00,914405.00,851.00,5.00,199.00,1.00,99899167304.00,NaN,9950931.00,97228126000150.00,NaN,0.00,0.00,3.00,6.00,40084.00,7113.00,99.00,120175.00,59502.84,57361.27,6614.92,4437.45,17550.00,3.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00

In [23]:
pd.options.display.max_seq_items = 113
base.columns

Index(['UF_ZI', 'ANO_CMPT', 'MES_CMPT', 'ESPEC', 'CGC_HOSP', 'N_AIH', 'IDENT',
       'CEP', 'MUNIC_RES', 'NASC', 'SEXO', 'UTI_MES_IN', 'UTI_MES_AN',
       'UTI_MES_AL', 'UTI_MES_TO', 'MARCA_UTI', 'UTI_INT_IN', 'UTI_INT_AN',
       'UTI_INT_AL', 'UTI_INT_TO', 'DIAR_ACOM', 'QT_DIARIAS', 'PROC_SOLIC',
       'PROC_REA', 'VAL_SH', 'VAL_SP', 'VAL_SADT', 'VAL_RN', 'VAL_ACOMP',
       'VAL_ORTP', 'VAL_SANGUE', 'VAL_SADTSR', 'VAL_TRANSP', 'VAL_OBSANG',
       'VAL_PED1AC', 'VAL_TOT', 'VAL_UTI', 'US_TOT', 'DT_INTER', 'DT_SAIDA',
       'DIAG_PRINC', 'DIAG_SECUN', 'COBRANCA', 'NATUREZA', 'NAT_JUR', 'GESTAO',
       'RUBRICA', 'IND_VDRL', 'MUNIC_MOV', 'COD_IDADE', 'IDADE', 'DIAS_PERM',
       'MORTE', 'NACIONAL', 'NUM_PROC', 'CAR_INT', 'TOT_PT_SP', 'CPF_AUT',
       'HOMONIMO', 'NUM_FILHOS', 'INSTRU', 'CID_NOTIF', 'CONTRACEP1',
       'CONTRACEP2', 'GESTRISCO', 'INSC_PN', 'SEQ_AIH5', 'CBOR', 'CNAER',
       'VINCPREV', 'GESTOR_COD', 'GESTOR_TP', 'GESTOR_CPF', 'GESTOR_DT',
       'CNES', 'CNPJ_MANT', 'INFEHOSP', 'CID_ASSO', 'CID_MORTE', 'COMPLEX',
       'FINANC', 'FAEC_TP', 'REGCT', 'RACA_COR', 'ETNIA', 'SEQUENCIA',
       'REMESSA', 'AUD_JUST', 'SIS_JUST', 'VAL_SH_FED', 'VAL_SP_FED',
       'VAL_SH_GES', 'VAL_SP_GES', 'VAL_UCI', 'MARCA_UCI', 'DIAGSEC1',
       'DIAGSEC2', 'DIAGSEC3', 'DIAGSEC4', 'DIAGSEC5', 'DIAGSEC6', 'DIAGSEC7',
       'DIAGSEC8', 'DIAGSEC9', 'TPDISEC1', 'TPDISEC2', 'TPDISEC3', 'TPDISEC4',
       'TPDISEC5', 'TPDISEC6', 'TPDISEC7', 'TPDISEC8', 'TPDISEC9'],
      dtype='object')